In [1]:
import numpy as np
import tensorflow as tf
# print(tf.__version__)
# print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

In [2]:
t1 = tf.Variable([1, 2, 3]) # 모델 파라미터와 같이 학습하면서 변하는 변수
t2 = tf.constant([1, 2, 3]) # dataset과 같이 변하지 않는 변수

In [3]:
print(t1)
print(t2)
print("====")
print(type(t1))
print(type(t2))

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
====
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [4]:
test_list = [1, 2, 3]
test_np = np.array([1, 2, 3])

print(type(test_list))
print(type(test_np))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
t1 = tf.constant(test_list)
t2 = tf.constant(test_np)

print(t1)
print(t2)
print(type(t1))
print(type(t2))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [6]:
t1 = tf.Variable(test_list)
t2 = tf.Variable(test_np)

print(t1)
print(t2)
print(type(t1))
print(type(t2))

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [7]:
t1 = tf.constant(test_list)
t2 = tf.Variable(test_list)

t3 = tf.constant(t2) # Variable tensor를 constant tensor로 변환할 수 없다.
t4 = tf.Variable(t1) # constant tensor는 Variable tensor로 변환할 수 있다.

In [8]:
t1 = tf.convert_to_tensor(test_list) # EagerTensor를 만든다.
t2 = tf.convert_to_tensor(test_np)

print(type(t1))
print(type(t2))

t3 = tf.Variable(test_list)
t4 = tf.convert_to_tensor(t3)

print(type(t3))
print(type(t4))

"""
convert_to_tensor는 결론적으로는 EagerTensor를 만들어 내는 것은 똑같다.
하지만 중간에 Variable tensor를 constant tensor로 바꿔줄 수 있다.
즉, 그 전까지의 forward propagation(순전파)의 기록을 없애버릴 수 있다.
"""

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


'\nconvert_to_tensor는 결론적으로는 EagerTensor를 만들어 내는 것은 똑같다.\n하지만 중간에 Variable tensor를 constant tensor로 바꿔줄 수 있다.\n즉, 그 전까지의 forward propagation(순전파)의 기록을 없애버릴 수 있다.\n'

In [9]:
test_list1 = [10, 20, 30]
test_list2 = [1, 2, 3]

t1 = tf.constant(test_list1)
t2 = tf.constant(test_list2)

t3 = t1 + t2
print(type(t3)) # EagerTensor + EagerTensor = EagerTensor

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [10]:
test_list1 = [10, 20, 30]
test_list2 = [1, 2, 3]

t1 = tf.constant(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1 + t2
print(type(t3)) # EagerTensor + ResourceTensor = EagerTensor

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [11]:
test_list1 = [10, 20, 30]
test_list2 = [1, 2, 3]

t1 = tf.Variable(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1 + t2
print(type(t3)) # Variable + Variable = EagerTensor

"""
Node들을 사칙연산 했을 때 EagerTensor가 만들어진다.
"""

<class 'tensorflow.python.framework.ops.EagerTensor'>


'\nNode들을 사칙연산 했을 때 EagerTensor가 만들어진다.\n'