In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.python.ops.gen_math_ops import mean

In [2]:
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([10, 20, 30])

print(t1 + t2)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)


In [3]:
lst1 = [1, 2, 3]
lst2 = [10, 20, 30]

print(lst1 + lst2)

"""
list끼리 더하면 concatenation으로 만들어 진다.
tensor끼리 더하면 각 element를 연산한다.
"""

[1, 2, 3, 10, 20, 30]


'\nlist끼리 더하면 concatenation으로 만들어 진다.\ntensor끼리 더하면 각 element를 연산한다.\n'

In [4]:
print(t1 + t2)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)
print(t1 % t2) # 나머지
print(t1 // t2) # 몫

tf.Tensor([11 22 33], shape=(3,), dtype=int32)
tf.Tensor([ -9 -18 -27], shape=(3,), dtype=int32)
tf.Tensor([10 40 90], shape=(3,), dtype=int32)
tf.Tensor([0.1 0.1 0.1], shape=(3,), dtype=float64)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)


In [5]:
# shape이 완전히 같은 경우
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t2 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)

t1 = tf.cast(t1, dtype=tf.int16)
t2 = tf.cast(t2, dtype=tf.int16)

print(t1.numpy())
print(t2.numpy())

print(t1 + t2)

[[-10   0  -8  -3]
 [ -1   4   0   8]
 [ -9  -3  -2   2]]
[[ 0  6  2 -8]
 [-2  1  3  1]
 [ 1  4  0 -8]]
tf.Tensor(
[[-10   6  -6 -11]
 [ -3   5   3   9]
 [ -8   1  -2  -6]], shape=(3, 4), dtype=int16)


In [6]:
# columns의 수가 같은 경우
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t2 = tf.random.normal(shape=(1, 4), mean=0, stddev=5)

t1 = tf.cast(t1, dtype=tf.int16)
t2 = tf.cast(t2, dtype=tf.int16)
t3 = t1 + t2

print(t1.numpy(), "\n")
print(t2.numpy(), "\n")
print(t3.numpy(), "\n")

[[ 0 -2  1  0]
 [-8  1 -6 -7]
 [ 3  3 -2 -1]] 

[[-4  7 -3  6]] 

[[ -4   5  -2   6]
 [-12   8  -9  -1]
 [ -1  10  -5   5]] 



In [7]:
# rows의 수가 같은 경우
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t2 = tf.random.normal(shape=(3, 1), mean=0, stddev=5)

t1 = tf.cast(t1, dtype=tf.int16)
t2 = tf.cast(t2, dtype=tf.int16)
t3 = t1 + t2

print(t1.numpy(), "\n")
print(t2.numpy(), "\n")
print(t3.numpy(), "\n")

[[-5 -4 -3 -2]
 [-8 13  2  4]
 [-4  5 -8  0]] 

[[-9]
 [-1]
 [-7]] 

[[-14 -13 -12 -11]
 [ -9  12   1   3]
 [-11  -2 -15  -7]] 



In [8]:
# rows와 columns의 수가 같은 경우
t1 = tf.random.normal(shape=(3, 1), mean=0, stddev=5)
t2 = tf.random.normal(shape=(1, 4), mean=0, stddev=5)

t1 = tf.cast(t1, dtype=tf.int16)
t2 = tf.cast(t2, dtype=tf.int16)
t3 = t1 + t2

print(t1.numpy(), "\n")
print(t2.numpy(), "\n")
print(t3.numpy(), "\n")

"""
tensorflow에서 간단한 tensor는 numpy나 numerical computation library처럼,
element-wise가 기본적인 operation으로 setting 되어 있다.
그리고 broadcasting은 연산을 행하려는 두 행렬의 shape이 맞지 않더라도
한 쪽을 다른 한 쪽에 맞출 수 있는 상황이라면 차원을 확장시켜 연산이 가능하도록 할 수 있다.
"""

[[6]
 [4]
 [1]] 

[[-1  0  7 -4]] 

[[ 5  6 13  2]
 [ 3  4 11  0]
 [ 0  1  8 -3]] 



'\ntensorflow에서 간단한 tensor는 numpy나 numerical computation library처럼,\nelement-wise가 기본적인 operation으로 setting 되어 있다.\n그리고 broadcasting은 연산을 행하려는 두 행렬의 shape이 맞지 않더라도\n한 쪽을 다른 한 쪽에 맞출 수 있는 상황이라면 차원을 확장시켜 연산이 가능하도록 할 수 있다.\n'

In [9]:
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t1 = tf.cast(t1, dtype=tf.int16)

print(t1)

tf.Tensor(
[[ 2  0 -1  0]
 [ 0  3  2  2]
 [ 3 -9  5 -1]], shape=(3, 4), dtype=int16)


In [10]:
tf.math.reduce_sum
tf.math.reduce_prod

tf.math.reduce_max
tf.math.reduce_min

tf.math.reduce_mean
tf.math.reduce_std
tf.math.reduce_variance

tf.math.reduce_all
tf.math.reduce_any

<function tensorflow.python.ops.math_ops.reduce_any(input_tensor, axis=None, keepdims=False, name=None)>

In [11]:
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t1 = tf.cast(t1, dtype=tf.int16)

t2 = tf.math.reduce_sum(t1) # 모든 elements의 합
t3 = tf.math.reduce_sum(t1, axis=0) # row를 없애라
t4 = tf.math.reduce_sum(t1, axis=1) # column을 없애라

print(t1.numpy(), t1.shape, "\n")
print(t2.numpy(), t2.shape, "\n")
print(t3.numpy(), t3.shape, "\n")
print(t4.numpy(), t4.shape, "\n")

[[-2 -3 -1 -6]
 [ 0  0 10 -2]
 [ 6  3  3 -6]] (3, 4) 

2 () 

[  4   0  12 -14] (4,) 

[-12   8   6] (3,) 



In [12]:
t1 = tf.random.normal(shape=(128, 128, 3), mean=0, stddev=5)
t1 = tf.cast(t1, dtype=tf.int16)

t2 = tf.math.reduce_sum(t1, axis=2) # 3차원 일때, 채널을 없애라

print(t1.shape, "\n")
print(t2.shape, "\n")

(128, 128, 3) 

(128, 128) 

