In [1]:
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds

In [2]:
train_x = np.arange(100).reshape(-1, 1)
train_y = 3 * train_x + 1

train_ds = tf.data.Dataset.from_tensor_slices((train_x, train_y))

tmp_ds = train_ds.take(10)

for x, y in tmp_ds:
  print(x)
  print(y, '\n')

tf.Tensor([0], shape=(1,), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32) 

tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32) 

tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor([7], shape=(1,), dtype=int32) 

tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([10], shape=(1,), dtype=int32) 

tf.Tensor([4], shape=(1,), dtype=int32)
tf.Tensor([13], shape=(1,), dtype=int32) 

tf.Tensor([5], shape=(1,), dtype=int32)
tf.Tensor([16], shape=(1,), dtype=int32) 

tf.Tensor([6], shape=(1,), dtype=int32)
tf.Tensor([19], shape=(1,), dtype=int32) 

tf.Tensor([7], shape=(1,), dtype=int32)
tf.Tensor([22], shape=(1,), dtype=int32) 

tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([25], shape=(1,), dtype=int32) 

tf.Tensor([9], shape=(1,), dtype=int32)
tf.Tensor([28], shape=(1,), dtype=int32) 



In [3]:
train_x = np.arange(100).reshape(-1, 1)
train_y = 3 * train_x + 1

train_validation_ds = tf.data.Dataset.from_tensor_slices((train_x, train_y))

n_train_validation = 100
n_train_ratio = 0.8
n_train = int(n_train_validation * n_train_ratio)

train_ds = train_validation_ds.take(n_train)

In [4]:
train_x = np.arange(100).reshape(-1, 1)
train_y = 3 * train_x + 1

train_validation_ds = tf.data.Dataset.from_tensor_slices((train_x, train_y))

n_train_validation = 100
n_train_ratio = 0.8

n_train = int(n_train_validation * n_train_ratio)
n_validation = n_train_validation - n_train

remaining_ds = train_validation_ds.skip(n_train)
validation_ds = remaining_ds.take(n_validation)

for x, y in validation_ds:
  print(x)
  print(y, '\n')
  break

tf.Tensor([80], shape=(1,), dtype=int32)
tf.Tensor([241], shape=(1,), dtype=int32) 



In [5]:
(train_validation_ds, test_ds), ds_info = tfds.load(
                                          name='mnist',
                                          shuffle_files=True,
                                          as_supervised=True,
                                          split=['train', 'test'],
                                          with_info=True)

print(ds_info.splits)

{'train': <SplitInfo num_examples=60000, num_shards=1>, 'test': <SplitInfo num_examples=10000, num_shards=1>}


In [6]:
n_train_validation = ds_info.splits['train'].num_examples
train_ratio = 0.8

n_train = int(n_train_validation * train_ratio)
n_validation = n_train_validation - n_train

train_ds = train_validation_ds.take(n_train)
remaining_ds = train_validation_ds.skip(n_train)
validation_ds = remaining_ds.take(n_validation)

train_ds = train_ds.shuffle(100).batch(32)
validation_ds = validation_ds.batch(32)
test_ds = test_ds.batch(32)